markdown: redcarpet
pygments: true
#plugins: ./_plugins
paginate: 8

safe: false

#站点基础配置
title: Wynelu's Blob
subTitle: 流水不腐，户枢不蠹
description: This is Wynelu's Blob.
url: http://wynelu.github.io
feed: /atom.xml

#菜单配置
nav:
  - text: 首页
    url: /index.html
    icon: icon-home
    class: home
  - text: 文章归档
    url: /archives.html
    icon: icon-reorder
    class: none
  - text: 关于我
    url: /contact.html
    icon: icon-envelope-alt
    class: none
  - text: 空白页
    url: /blank.html
    icon: icon-heart
    class: none
  - text: 博客源代码
    url: https://github.com/wynelu/wynelu.github.io
    icon: icon-github
    class: none

page:
  - text: 文章分类
    url: /archives.html
    last: true
  - text: 友情链接
    url: /links.html
    last: true
  - text: 关于我
    url: /contact.html
    last: false

author:
  name: wynelu
